sudo: required
dist: trusty
language: python
services:
- docker
branches:
  only:
  - master
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y gzip
script:
- sudo service docker restart
- git clone https://github.com/mapbox/mbutil.git
- "./task/generate-tiles.sh"
- "./task/deploy.sh"
env:
  global:
    secure: Ykr+v6bNKPO9IYnEQHvQlGox2cQVXwcSJMnqc1czw/9dwmCm+mR1X1dRqO4BdidrWpxV5r+murXYGXbWrTytA1GDzvOdXce7IOJkLjgEylC0yFkvsmudkhqTXSupS6qKURvGUoaza5E5AJ0DjSNtGJBlT0/yfEFvhPgWo2BoOsHzL+lF6OifHr1NhxUkiFAKYiTIUceMYP5qWmIQ+0nWiGDyahv2I+mVFJEALCYB0v/c80e1Ys/mf6OYkIZFn699pJ+MCHaBxoByDIiASWnGy3D82oPX9a7Nq6KK6fT2Rkqvw0xXCDxlzpSvFBuIfvjxnQEgd4OK+uP6t3r3yQeWK+WpN3yALIdl+TkL6WALpIRSCcaaSoJCV2m3MAMjcS7xSlO5zEbuJ/3ZpU+LZ+GNCUux6iqq9D8do92/H0ucCE1wKXvq3e116l9S3Y47N1tzRwDjOCKtHEjwZGhd5tTRQceDqyTeEaklM3w5KBubBkFhPSdF8HV82RN3dd+0JIxc6bKGBg2Gvfl140lGB+FA4Bz3NlZC+mvbpvDAzt01HrD+Cw69m8+zlqn59wYI6450xfv5LRspQiaKr4E/qi91mlfQzUivvxWwYkO+2/Lyky3hjOM/HKwPVnUJeJvrMr+wDcApjWkaKKb46vBAhG+652Cx0nsxnykJjkYTofOmZZE=
