sudo: required
dist: trusty
language: python
services:
- docker
branches:
  only:
  - master
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.5
    packages:
    - libstdc++6
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y gzip
script:
- nvm install 4
- nvm use 4
- npm install
- sudo service docker restart
- git clone https://github.com/mapbox/mbutil.git
- "./task/test.sh"
- "./task/generate-tiles.sh"
- "./task/deploy.sh"
env:
  global:
    secure: dSzV32E3awx2MVw7K2LoS2AQlp/BsgtFaQezxdukXP56VE7zCef2BPoXltU+yx0teNIxEjuc0clI0pFLbVtmpyZ+qa3rSEJS0BcwkR/Js7InELvPR8Gr/3iQtILYgtEpVNJZPih+INxwiNQSUKkaJAlEg/kXkryyDyqPfg6TZ+vM4e5PEZkIm7wxfOwNoIqZBhtNGThVnBUlxJTDTOO28Zr4S5DDU9rZzcaPRZU9uSSM3/q/CbX4ab1vAQTOewIcuPUhfcMdI4xwW7QhclNz8bnsRnSQBOd0U/33lyGF3ZAApcF7U3vHCghlm2pRCuqWNcFALGKOIndDFILGafLzDp9PnEF9gPyFxlJ20tSVZ+rdSS0+fiMRK9TOGlEImExasMnPYfiDqoU3XEjyu8WLzsbUwERaGX/p8/9A2wUljCiDXn6PEkMyZEge4H3rP5XHTv7X3CxDH2sW2U9C4gxdjjRUAkI9PQZ/cbIdF3iWSEJKpSJLF+iKkBEZ46WwQXvz3fZAll4Mgt+JIYcFZQHe/YCNjHqHGJBkTaaFqmappFzx2FcKPGYPkTOWmu+OKGgNdcd3/pPirVh22b9DBa8Di/ziZT77D5hjisT8ZrhhALfEj9miVOA5DFrogGId0Zgrjaz0yAlEGysOnxo+DATzhOtrsmm0SBM6Cu6Qb53ngZM=
